# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicZineFighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('publisher', models.TextField()),
                ('origin', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('deck', models.TextField(null=True)),
                ('api_detail_url', models.TextField(null=True)),
                ('site_detail_url', models.TextField(null=True)),
                ('first_appeared_in_issue', models.TextField(null=True)),
                ('count_of_issue_appearances', models.IntegerField(null=True)),
                ('birth', models.TextField(null=True)),
                ('real_name', models.TextField(null=True)),
                ('aliases', models.TextField(null=True)),
                ('date_added', models.DateTimeField(null=True)),
                ('date_last_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
