# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comiczinefighter',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
