# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0002_auto_20170129_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comiczinefighter',
            name='publisher',
            field=models.TextField(null=True),
        ),
    ]
